blog/urls.py
from django.urls.conf import path,include
from . import views

app_name='blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path ('<int:blog_id>/', views.individualblog, name='individualblog')

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls.conf import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/urls.py
from . import views
from django.urls.conf import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
   path('', views.home, name='home'),
]

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField (max_length = 1000)
    date = models.DateField()

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    image= models.ImageField(upload_to="portfolio/images/")
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def blog(request):
    Blogs = Blog.objects.order_by('-date') [:2]
    return render(request,'blog/blog.html', {'Blogs': Blogs})

def individualblog(request,blog_id):
    individualblog = get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/individualblog.html',{'blogid':individualblog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    Projects = Project.objects.all()
    return render(request,'portfolio/home.html',{'Projects': Projects})

blog/templates/blog/blog.html
{% include 'portfolio/base.html' %}
{% block content %}
<h2> subbu has written {{ blog.count }} blog {{ blog.count|pluralize  }} </h2>
{% for blog in Blogs %}<br>
<a href="{% url 'blog:individualblog' blog.id %}"> <h2> {{ blog.title }} </h2> </a> <br>
{{ blog.description|truncatechars:100 }}<br>
{{ blog.date|date:'M d Y' }}
{% endfor %}
{% endblock %}

blog/templates/blog/individualblog.html
{% include 'portfolio/base.html' %}
{% block content %}
<b>{{ blogid.title }}</b><br>
{{ blogid.date|date:'d F Y'| upper}}
{{ blogid.description}}
{% endblock %}

portfolio/templates/portfolio/base.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Subbu Portfolio</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

{% block content %}
{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% include 'portfolio/base.html' %}
{% block content %}
{% load static %}
<img src ="{% static 'subbu/portfolio/img/dog.jpg' %}">
<h1> This is Subbu home Page :)</h1>
{% for project in Projects %}
{{ project.title }}
{{ project.description }}
<br>
<img src="{{ project.image.url }}" height="40" width="40">
<br>
{% if project.url %}
<a href="{{ project.url }}"> Click Here</a>
<br>
{% endif %}
{% endfor %}
{% endblock %}